@extends('layouts.app')

@section('title', 'Buscar tarifas · EasyMove')

@section('content')
<style>
    /* ==== Animations ==== */
    @keyframes fadeInUp {
        from { opacity: 0; transform: translateY(16px); }
        to   { opacity: 1; transform: translateY(0); }
    }
    .animate-fadeInUp { animation: fadeInUp .55s ease-out forwards; }

    @keyframes slideInScale {
        from { opacity: 0; transform: scale(.95); }
        to   { opacity: 1; transform: scale(1); }
    }
    .animate-slideInScale { animation: slideInScale .25s ease-out forwards; }

    @keyframes shimmer {
        0% { background-position: -1000px 0; }
        100% { background-position: 1000px 0; }
    }

    /* ==== Search hero ==== */
    .search-hero {
        position: relative;
        overflow: hidden;
        border-radius: 1.5rem;
        border: 1px solid rgb(226 232 240);
        background:
            radial-gradient(1200px 400px at 0% -10%, rgba(14,165,233,.18), transparent 60%),
            radial-gradient(1000px 360px at 100% 0%, rgba(168,85,247,.18), transparent 60%),
            linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);
    }
    html.dark .search-hero {
        border-color: rgb(30 41 59);
        background:
            radial-gradient(1200px 400px at 0% -10%, rgba(14,165,233,.20), transparent 60%),
            radial-gradient(1000px 360px at 100% 0%, rgba(168,85,247,.18), transparent 60%),
            linear-gradient(180deg, #0f172a 0%, #020617 100%);
    }

    /* ==== Inputs ==== */
    .field-input {
        width: 100%;
        padding: .85rem 1rem;
        border-radius: .75rem;
        border: 1px solid rgb(226 232 240);
        background: rgb(255 255 255);
        color: rgb(15 23 42);
        transition: border-color .2s ease, box-shadow .2s ease, background .2s ease;
    }
    .field-input:focus {
        outline: none;
        border-color: rgb(99 102 241);
        box-shadow: 0 0 0 4px rgba(99,102,241,.18);
    }
    html.dark .field-input {
        background: rgb(15 23 42);
        border-color: rgb(51 65 85);
        color: rgb(241 245 249);
    }
    html.dark .field-input:focus {
        border-color: rgb(129 140 248);
        box-shadow: 0 0 0 4px rgba(129,140,248,.22);
    }

    .field-label {
        display: flex; align-items: center; gap: .5rem;
        font-size: .8rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: .05em;
        color: rgb(71 85 105);
        margin-bottom: .5rem;
    }
    html.dark .field-label { color: rgb(148 163 184); }

    /* ==== Chips ==== */
    .chip {
        padding: .55rem 1.1rem;
        border: 1.5px solid rgb(226 232 240);
        border-radius: 9999px;
        background: rgb(255 255 255);
        color: rgb(71 85 105);
        font-weight: 600;
        font-size: .875rem;
        cursor: pointer;
        transition: all .25s ease;
    }
    html.dark .chip { background: rgb(30 41 59); border-color: rgb(51 65 85); color: rgb(203 213 225); }
    .chip:hover {
        border-color: rgb(99 102 241);
        color: rgb(99 102 241);
        transform: translateY(-1px);
    }
    .chip.active {
        background: linear-gradient(135deg, #0ea5e9, #6366f1);
        border-color: transparent;
        color: white;
        box-shadow: 0 6px 18px -4px rgba(99,102,241,.55);
    }

    /* ==== Result cards (generated by JS) ==== */
    .result-card {
        background: white;
        border: 1px solid rgb(226 232 240);
        border-radius: 1rem;
        overflow: hidden;
        transition: transform .3s ease, box-shadow .3s ease, border-color .3s ease;
        display: flex; flex-direction: column;
    }
    html.dark .result-card { background: rgb(15 23 42); border-color: rgb(51 65 85); }
    .result-card:hover {
        transform: translateY(-4px);
        box-shadow: 0 24px 40px -20px rgba(15,23,42,.25);
        border-color: rgba(99,102,241,.5);
    }

    /* ==== Modern spinner ==== */
    .spinner-modern {
        width: 56px; height: 56px;
        border-radius: 50%;
        border: 4px solid rgba(99,102,241,.18);
        border-top-color: rgb(99 102 241);
        animation: spin 1s linear infinite;
        margin: 0 auto;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    /* ==== Tom Select dark-friendly tweaks ==== */
    .ts-control { padding: .85rem 1rem !important; border-radius: .75rem !important; min-height: auto !important; }
    html.dark .ts-control { background: rgb(15 23 42) !important; border-color: rgb(51 65 85) !important; color: rgb(241 245 249) !important; }
    html.dark .ts-dropdown { background: rgb(15 23 42) !important; border-color: rgb(51 65 85) !important; color: rgb(241 245 249) !important; }
    html.dark .ts-dropdown .option { color: rgb(203 213 225) !important; }
    html.dark .ts-dropdown .active { background: rgb(30 41 59) !important; color: white !important; }

    /* ==== Badges in result cards ==== */
    .badge-eco, .badge-bestseller, .badge-sin-permanencia {
        display: inline-flex; align-items: center; gap: .35rem;
        padding: .25rem .65rem;
        border-radius: 9999px;
        font-size: .7rem; font-weight: 700; text-transform: uppercase; letter-spacing: .04em;
    }
    .badge-eco { background: rgba(16,185,129,.12); color: rgb(5 150 105); }
    .badge-bestseller { background: rgba(245,158,11,.14); color: rgb(180 83 9); }
    .badge-sin-permanencia { background: rgba(99,102,241,.14); color: rgb(67 56 202); }

    /* ==== Flip card (Comparador <-> Explorar zona) ==== */
    .flip-wrapper { perspective: 2200px; }
    .flip-inner {
        position: relative;
        transition: transform .85s cubic-bezier(.2,.7,.2,1);
        transform-style: preserve-3d;
    }
    .flip-wrapper.flipped .flip-inner { transform: rotateY(180deg); }
    .flip-face {
        backface-visibility: hidden;
        -webkit-backface-visibility: hidden;
    }
    .flip-back {
        position: absolute;
        inset: 0;
        transform: rotateY(180deg);
    }
    .mode-tabs {
        display: inline-flex;
        align-items: center;
        gap: .35rem;
        padding: .4rem;
        border-radius: 9999px;
        border: 1px solid rgba(99,102,241,.25);
        background: linear-gradient(135deg, rgba(255,255,255,.96), rgba(241,245,249,.95));
        backdrop-filter: blur(8px);
        box-shadow: 0 14px 30px -18px rgba(15,23,42,.3);
    }
    html.dark .mode-tabs {
        border-color: rgba(129,140,248,.4);
        background: linear-gradient(135deg, rgba(15,23,42,.92), rgba(30,41,59,.85));
    }
    .mode-tab {
        display: inline-flex;
        align-items: center;
        gap: .55rem;
        padding: .65rem 1.15rem;
        border-radius: 9999px;
        font-weight: 800;
        font-size: .9rem;
        color: rgb(30 41 59);
        border: 1px solid transparent;
        background: rgba(255,255,255,.75);
        box-shadow: inset 0 0 0 1px rgba(148,163,184,.3);
        transition: all .2s ease;
    }
    .mode-tab:hover { transform: translateY(-1px); }
    html.dark .mode-tab {
        color: rgb(226 232 240);
        background: rgba(15,23,42,.6);
        box-shadow: inset 0 0 0 1px rgba(71,85,105,.5);
    }
    .mode-tab.active {
        background: linear-gradient(135deg, #0ea5e9, #6366f1);
        color: white;
        box-shadow: 0 10px 22px -14px rgba(99,102,241,.6);
    }
    .mode-tab.primary.active {
        background: linear-gradient(135deg, #2563eb, #4f46e5);
        box-shadow: 0 12px 24px -14px rgba(37,99,235,.65);
    }
    .mode-tab.alt.active {
        background: linear-gradient(135deg, #f97316, #ef4444);
        box-shadow: 0 10px 22px -14px rgba(239,68,68,.6);
    }

    .zone-shortcut-btn {
        display: inline-flex;
        align-items: center;
        gap: .5rem;
        padding: .6rem 1rem;
        border-radius: 9999px;
        border: 1px solid rgba(244,63,94,.25);
        background: rgba(255,255,255,.9);
        color: rgb(190 18 60);
        font-weight: 700;
        font-size: .85rem;
        transition: transform .2s ease, box-shadow .2s ease, background .2s ease;
    }
    .zone-shortcut-btn:hover {
        transform: translateY(-1px);
        box-shadow: 0 10px 24px -14px rgba(244,63,94,.45);
        background: rgba(255,228,230,.8);
    }
    html.dark .zone-shortcut-btn {
        background: rgba(15,23,42,.75);
        border-color: rgba(244,63,94,.35);
        color: rgb(253 164 175);
    }

    /* Map area */
    .map-frame-wrap {
        position: relative;
        border-radius: 1rem;
        overflow: hidden;
        border: 1.5px solid rgb(226 232 240);
        background: rgb(248 250 252);
        height: 560px;
        transition: border-color .3s ease, box-shadow .3s ease;
    }
    html.dark .map-frame-wrap {
        border-color: rgb(51 65 85);
        background: rgb(15 23 42);
    }
    #mapSection .map-frame-wrap {
        border-color: rgb(239,68,68);
        box-shadow: 0 16px 32px -20px rgba(239,68,68,.45);
        background: linear-gradient(135deg, rgba(254,226,226,.35), rgb(248 250 252) 55%);
    }
    html.dark #mapSection .map-frame-wrap {
        border-color: rgb(248,113,113);
        box-shadow: 0 16px 32px -20px rgba(239,68,68,.55);
        background: linear-gradient(135deg, rgba(127,29,29,.55), rgb(15 23 42) 55%);
    }
    #leafletMap { width: 100%; height: 100%; }

    /* Places list */
    .places-list-wrap {
        border: 1.5px solid rgb(226 232 240);
        border-radius: 1rem;
        background: white;
        height: 560px;
        display: flex;
        flex-direction: column;
        overflow: hidden;
        transition: border-color .3s ease, box-shadow .3s ease, background-color .3s ease;
    }
    html.dark .places-list-wrap { background: rgb(15 23 42); border-color: rgb(51 65 85); }
    #mapSection .places-list-wrap {
        border-color: rgb(239,68,68);
        box-shadow: 0 16px 32px -20px rgba(239,68,68,.45);
        background: linear-gradient(180deg, rgba(254,226,226,.5) 0%, rgba(254,226,226,.15) 100%);
    }
    html.dark #mapSection .places-list-wrap {
        border-color: rgb(248,113,113);
        box-shadow: 0 16px 32px -20px rgba(239,68,68,.55);
        background: linear-gradient(180deg, rgba(127,29,29,.65) 0%, rgba(127,29,29,.2) 100%);
    }
    .places-list-header {
        padding: .9rem 1rem;
        border-bottom: 1px solid rgb(226 232 240);
        font-size: .8rem; font-weight: 700;
        text-transform: uppercase; letter-spacing: .05em;
        color: rgb(71 85 105);
        display: flex; align-items: center; justify-content: space-between; gap: .5rem;
    }
    html.dark .places-list-header { border-color: rgb(51 65 85); color: rgb(148 163 184); }
    .places-list { overflow-y: auto; flex: 1; }
    .place-item {
        display: flex; gap: .75rem; align-items: flex-start;
        padding: .85rem 1rem;
        border-bottom: 1px solid rgb(241 245 249);
        cursor: pointer;
        transition: background .15s ease, border-color .15s ease;
    }
    html.dark .place-item { border-color: rgb(30 41 59); }
    .place-item:hover {
        background: rgb(248 250 252);
    }
    html.dark .place-item:hover { background: rgb(30 41 59); }
    .place-item.active {
        background: rgba(99,102,241,.08);
        border-left: 3px solid rgb(99 102 241);
        padding-left: calc(1rem - 3px);
    }
    html.dark .place-item.active { background: rgba(129,140,248,.12); }
    .place-icon {
        width: 38px; height: 38px;
        border-radius: .6rem;
        display: grid; place-items: center;
        flex-shrink: 0;
        font-size: 1.05rem;
    }
    .place-icon.bar { background: rgba(245,158,11,.14); color: rgb(180 83 9); }
    .place-icon.restaurant { background: rgba(239,68,68,.14); color: rgb(185 28 28); }
    .place-icon.cafe { background: rgba(120,53,15,.14); color: rgb(120 53 15); }
    .place-icon.pub { background: rgba(168,85,247,.14); color: rgb(126 34 206); }
    .place-icon.fast_food { background: rgba(16,185,129,.14); color: rgb(5 150 105); }
    html.dark .place-icon.cafe { color: rgb(217 119 6); }
    .place-info { min-width: 0; flex: 1; }
    .place-name {
        font-weight: 700; font-size: .9rem;
        color: rgb(15 23 42);
        overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    }
    html.dark .place-name { color: rgb(241 245 249); }
    .place-meta { font-size: .72rem; color: rgb(100 116 139); margin-top: .15rem; }
    html.dark .place-meta { color: rgb(148 163 184); }
    .place-tag {
        display: inline-block;
        font-size: .65rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: .04em;
        padding: .1rem .45rem;
        border-radius: 9999px;
        margin-right: .25rem;
    }
    .place-tag.bar { background: rgba(245,158,11,.14); color: rgb(180 83 9); }
    .place-tag.restaurant { background: rgba(239,68,68,.14); color: rgb(185 28 28); }
    .place-tag.cafe { background: rgba(120,53,15,.14); color: rgb(120 53 15); }
    .place-tag.pub { background: rgba(168,85,247,.14); color: rgb(126 34 206); }
    .place-tag.fast_food { background: rgba(16,185,129,.14); color: rgb(5 150 105); }

    .places-list-loading, .places-list-empty {
        padding: 2rem 1rem; text-align: center;
        color: rgb(100 116 139); font-size: .85rem;
    }
    html.dark .places-list-loading, html.dark .places-list-empty { color: rgb(148 163 184); }

    /* Filtros tipo en cabecera de la lista */
    .place-filter {
        font-size: .7rem; font-weight: 600;
        padding: .25rem .55rem;
        border-radius: 9999px;
        border: 1px solid rgb(226 232 240);
        color: rgb(71 85 105);
        background: white;
        cursor: pointer;
        transition: all .15s ease;
    }
    html.dark .place-filter { background: rgb(15 23 42); border-color: rgb(51 65 85); color: rgb(203 213 225); }
    .place-filter.active {
        background: rgb(99 102 241);
        color: white;
        border-color: transparent;
    }

    /* Leaflet popup tweaks (dark mode friendly) */
    .leaflet-popup-content-wrapper, .leaflet-popup-tip {
        background: white; color: rgb(15 23 42);
    }
    html.dark .leaflet-popup-content-wrapper, html.dark .leaflet-popup-tip {
        background: rgb(15 23 42); color: rgb(241 245 249);
    }
    html.dark .leaflet-control-attribution {
        background: rgba(15,23,42,.8) !important;
        color: rgb(148 163 184) !important;
    }
    html.dark .leaflet-control-attribution a { color: rgb(165 180 252) !important; }

    /* ==== Benefit items ==== */
    .benefit-item {
        display: inline-flex; align-items: center; gap: .35rem;
        padding: .35rem .65rem;
        border-radius: .5rem;
        font-size: .75rem;
        background: rgb(248 250 252);
        color: rgb(71 85 105);
        margin: .15rem;
    }
    html.dark .benefit-item { background: rgb(30 41 59); color: rgb(203 213 225); }
    .benefit-item.eco { background: rgba(16,185,129,.12); color: rgb(5 150 105); }

    /* ==== MODO ZONA: Cambio de colores completo ==== */
    .flip-wrapper.flipped .search-hero {
        background:
            radial-gradient(1200px 400px at 0% -10%, rgba(239,68,68,.18), transparent 60%),
            radial-gradient(1000px 360px at 100% 0%, rgba(248,113,113,.18), transparent 60%),
            linear-gradient(180deg, #ffffff 0%, #fef2f2 100%);
    }
    html.dark .flip-wrapper.flipped .search-hero {
        background:
            radial-gradient(1200px 400px at 0% -10%, rgba(239,68,68,.22), transparent 60%),
            radial-gradient(1000px 360px at 100% 0%, rgba(248,113,113,.18), transparent 60%),
            linear-gradient(180deg, #7f1d1d 0%, #450a0a 100%);
    }
    .flip-wrapper.flipped .search-hero { border-color: rgba(239,68,68,.35); }
    html.dark .flip-wrapper.flipped .search-hero { border-color: rgba(248,113,113,.45); }

    /* Inputs en modo zona */
    .flip-wrapper.flipped .field-input {
        border-color: rgba(239,68,68,.45);
    }
    .flip-wrapper.flipped .field-input:focus {
        border-color: rgb(220 38 38);
        box-shadow: 0 0 0 4px rgba(239,68,68,.18);
    }
    html.dark .flip-wrapper.flipped .field-input {
        border-color: rgba(248,113,113,.5);
    }
    html.dark .flip-wrapper.flipped .field-input:focus {
        border-color: rgb(244 63 94);
        box-shadow: 0 0 0 4px rgba(244,63,94,.22);
    }

    /* Labels en modo zona */
    .flip-wrapper.flipped .field-label {
        color: rgb(159 18 57);
    }
    html.dark .flip-wrapper.flipped .field-label {
        color: rgb(254 205 211);
    }

    /* Badge en modo zona */
    .flip-wrapper.flipped .inline-flex.items-center.gap-2.px-3.py-1 {
        background: rgba(239,68,68,.15) !important;
        border-color: rgba(239,68,68,.35) !important;
        color: rgb(185 28 28) !important;
    }
    html.dark .flip-wrapper.flipped .inline-flex.items-center.gap-2.px-3.py-1 {
        background: rgba(248,113,113,.15) !important;
        border-color: rgba(248,113,113,.4) !important;
        color: rgb(253 164 175) !important;
    }

    /* Botón en modo zona */
    .flip-wrapper.flipped .btn-brand {
        background: linear-gradient(135deg, #ef4444, #e11d48);
        box-shadow: 0 10px 32px -10px rgba(239,68,68,.45);
    }
    .flip-wrapper.flipped .btn-brand:hover {
        background: linear-gradient(135deg, #dc2626, #be123c);
        box-shadow: 0 14px 40px -12px rgba(239,68,68,.55);
        transform: translateY(-2px);
    }
    html.dark .flip-wrapper.flipped .btn-brand {
        background: linear-gradient(135deg, #dc2626, #be123c);
        box-shadow: 0 10px 32px -10px rgba(239,68,68,.55);
    }
    html.dark .flip-wrapper.flipped .btn-brand:hover {
        background: linear-gradient(135deg, #b91c1c, #991b1b);
        box-shadow: 0 14px 40px -12px rgba(239,68,68,.65);
    }

    /* Ring brand en modo zona */
    .flip-wrapper.flipped .ring-brand {
        --tw-ring-color: rgba(239,68,68,.25);
    }

    /* Filtros avanzados botón en modo zona */
    .flip-wrapper.flipped #toggleFiltersBtn {
        color: rgb(220 38 38);
    }
    .flip-wrapper.flipped #toggleFiltersBtn:hover {
        color: rgb(185 28 28);
    }
    html.dark .flip-wrapper.flipped #toggleFiltersBtn {
        color: rgb(253 230 138);
    }
    html.dark .flip-wrapper.flipped #toggleFiltersBtn:hover {
        color: rgb(253 224 71);
    }

    /* Heading de filtros avanzados en modo zona */
    .flip-wrapper.flipped #advancedFilters h3 {
        color: rgb(220 38 38);
    }
    html.dark .flip-wrapper.flipped #advancedFilters h3 {
        color: rgb(254 205 211);
    }
    .flip-wrapper.flipped #advancedFilters h3 i {
        color: rgb(220 38 38) !important;
    }
    html.dark .flip-wrapper.flipped #advancedFilters h3 i {
        color: rgb(248 113 113) !important;
    }

    /* Botones de filtros avanzados en modo zona */
    .flip-wrapper.flipped #applyFiltersBtn {
        background: linear-gradient(135deg, #ef4444, #e11d48);
        border-color: transparent;
    }
    .flip-wrapper.flipped #applyFiltersBtn:hover {
        background: linear-gradient(135deg, #dc2626, #be123c);
    }
    html.dark .flip-wrapper.flipped #applyFiltersBtn {
        background: linear-gradient(135deg, #dc2626, #be123c);
    }
    html.dark .flip-wrapper.flipped #applyFiltersBtn:hover {
        background: linear-gradient(135deg, #b91c1c, #991b1b);
    }

    /* Aviso para invitados en modo zona */
    .flip-wrapper.flipped .mt-6.p-4.rounded-xl {
        background: linear-gradient(to right, rgba(239,68,68,.08), rgba(244,63,94,.08)) !important;
        border-color: rgba(239,68,68,.3) !important;
    }
    .flip-wrapper.flipped .mt-6.p-4.rounded-xl p {
        color: rgb(153 27 27) !important;
    }
    .flip-wrapper.flipped .mt-6.p-4.rounded-xl i {
        color: rgb(239 68 68) !important;
    }
    html.dark .flip-wrapper.flipped .mt-6.p-4.rounded-xl {
        background: linear-gradient(to right, rgba(127,29,29,.4), rgba(127,29,29,.35)) !important;
        border-color: rgba(248,113,113,.4) !important;
    }
    html.dark .flip-wrapper.flipped .mt-6.p-4.rounded-xl p {
        color: rgb(254 205 211) !important;
    }
    html.dark .flip-wrapper.flipped .mt-6.p-4.rounded-xl i {
        color: rgb(248 113 113) !important;
    }
</style>

<div class="space-y-8">

    {{-- ============================ HERO + FORMULARIO (FLIP) ============================ --}}
    <div id="heroFlip" class="flip-wrapper relative">
      @auth
        <div class="flex justify-end mb-4">
            <div class="mode-tabs" role="tablist" aria-label="Cambiar modo">
                <button type="button" class="mode-tab primary active" data-mode="tarifa" onclick="setMode('tarifa')" role="tab" aria-selected="true">
                    <i class="bi bi-stars"></i>
                    Comparador
                </button>
                <button type="button" class="mode-tab alt" data-mode="zone" onclick="setMode('zone')" role="tab" aria-selected="false">
                    <i class="bi bi-search-heart"></i>
                    Buscar bares y restaurantes
                </button>
            </div>
        </div>
      @endauth

      <div class="flip-inner">

        {{-- ============================ CARA FRONTAL: COMPARADOR ============================ --}}
        <div class="flip-face search-hero p-6 sm:p-10 shadow-sm">
        <div class="mb-8 max-w-3xl">
            <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-white/70 dark:bg-slate-900/70 border border-slate-200 dark:border-slate-700 text-indigo-600 dark:text-indigo-400 mb-4">
                <i class="bi bi-stars"></i> Comparador inteligente
            </div>
            <h1 class="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-slate-900 dark:text-white">
                Encuentra tu tarifa perfecta
                <span class="block gradient-text">en segundos.</span>
            </h1>
            <p class="mt-3 text-base sm:text-lg text-slate-600 dark:text-slate-300">
                Selecciona el tipo de servicio y tu código postal. Nosotros te enseñamos las mejores opciones disponibles.
            </p>
        </div>

        <form id="searchForm" class="space-y-6">
            @csrf
            <div class="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                {{-- Tipo de servicio --}}
                <div>
                    <label for="id_tipo_servicio" class="field-label">
                        <i class="bi bi-list-check"></i>Tipo de servicio
                    </label>
                    <select id="id_tipo_servicio" name="id_tipo_servicio" required class="field-input">
                        <option value="">— Seleccionar —</option>
                        @foreach ($tiposServicios as $tipo)
                            <option value="{{ $tipo->id_tipo_servicio }}">{{ $tipo->nombre }}</option>
                        @endforeach
                    </select>
                </div>

                {{-- Provincia --}}
                <div>
                    <label for="provincia" class="field-label">
                        <i class="bi bi-map"></i>Provincia
                    </label>
                    <select id="provincia" name="provincia" required class="field-input">
                        <option value="">— Seleccionar —</option>
                        @foreach ($provincias as $prov)
                            <option value="{{ $prov }}">{{ $prov }}</option>
                        @endforeach
                    </select>
                </div>

                {{-- Código postal (depende de provincia) --}}
                <div>
                    <label for="codigo_postal" class="field-label">
                        <i class="bi bi-geo-alt"></i>Código postal
                    </label>
                    <select id="codigo_postal" name="codigo_postal" required class="field-input" disabled>
                        <option value="">— Selecciona una provincia primero —</option>
                    </select>
                </div>

                {{-- Botón --}}
                <div>
                    <button type="submit" class="btn-brand ring-brand w-full inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl text-white font-bold text-base">
                        <i class="bi bi-search text-lg"></i>
                        Buscar tarifas
                    </button>
                </div>
            </div>

            {{-- ============== FILTROS AVANZADOS (auth only) ============== --}}
            @auth
                <button type="button" id="toggleFiltersBtn" onclick="toggleAdvancedFilters()"
                        class="inline-flex items-center gap-2 text-sm font-semibold text-indigo-600 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-300 transition">
                    <i class="bi bi-sliders"></i>
                    <span id="filterToggleText">Mostrar filtros avanzados</span>
                </button>

                <div id="advancedFilters" class="hidden pt-8 border-t border-slate-200 dark:border-slate-700 space-y-6 animate-fadeInUp">
                    <h3 class="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        <i class="bi bi-funnel-fill text-indigo-500"></i>Filtros avanzados
                    </h3>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label class="field-label"><i class="bi bi-currency-euro"></i>Rango de precio (€/mes)</label>
                            <div class="flex items-center gap-3">
                                <input type="number" id="min_precio" name="min_precio" step="0.01" min="0" placeholder="Mín" class="field-input">
                                <span class="text-slate-400 font-bold">—</span>
                                <input type="number" id="max_precio" name="max_precio" step="0.01" min="0" placeholder="Máx" class="field-input">
                            </div>
                        </div>

                        <div>
                            <label for="ordenar_por" class="field-label"><i class="bi bi-sort-down"></i>Ordenar por</label>
                            <select id="ordenar_por" name="ordenar_por" class="field-input">
                                <option value="precio_asc">Precio: menor a mayor</option>
                                <option value="precio_desc">Precio: mayor a menor</option>
                                <option value="reciente">Más reciente</option>
                                <option value="nombre_asc">Alfabético (A-Z)</option>
                            </select>
                        </div>
                    </div>

                    <div>
                        <label class="field-label"><i class="bi bi-calendar-check"></i>Permanencia</label>
                        <div class="flex flex-wrap gap-2">
                            <button type="button" class="chip" onclick="toggleChip(this, 'sin_permanencia')">Sin permanencia</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '1mes')">1 mes</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '3meses')">3 meses</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '6meses')">6 meses</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '12meses')">12 meses</button>
                        </div>
                    </div>

                    <div>
                        <label for="buscar_nombre" class="field-label"><i class="bi bi-search"></i>Buscar por nombre</label>
                        <input type="text" id="buscar_nombre" name="buscar_nombre" placeholder="Ej: Plan Premium, Básico, Eco…" class="field-input">
                    </div>

                    <div class="flex gap-3 pt-4 border-t border-slate-200 dark:border-slate-700">
                        <button type="submit" id="applyFiltersBtn" class="flex-1 inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold transition">
                            <i class="bi bi-check-lg"></i>Aplicar filtros
                        </button>
                        <button type="button" id="clearFiltersBtn" class="flex-1 inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-900 dark:text-white font-bold transition">
                            <i class="bi bi-arrow-counterclockwise"></i>Limpiar
                        </button>
                    </div>
                </div>
            @endauth
        </form>

        {{-- Aviso para invitados --}}
        @guest
            <div class="mt-6 p-4 rounded-xl bg-gradient-to-r from-sky-50 to-indigo-50 dark:from-sky-950/40 dark:to-indigo-950/40 border border-sky-100 dark:border-sky-900">
                <p class="text-sm text-sky-900 dark:text-sky-200 flex items-start gap-3">
                    <i class="bi bi-info-circle text-lg mt-0.5 flex-shrink-0 text-sky-500"></i>
                    <span>
                        <strong>Modo invitado:</strong> solo verás 2 resultados.
                        <a href="{{ route('login') }}" class="underline font-bold hover:text-sky-700 dark:hover:text-sky-300">Inicia sesión</a> para ver todas las opciones y guardar tus comparaciones.
                    </span>
                </p>
            </div>
        @endguest
        </div>
        {{-- /CARA FRONTAL --}}

        @auth
        {{-- ============================ CARA TRASERA: EXPLORAR ZONA ============================ --}}
        <div class="flip-face flip-back search-hero p-6 sm:p-10 shadow-sm">
            <div class="mb-8 max-w-3xl">
                <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-white/70 dark:bg-slate-900/70 border border-slate-200 dark:border-slate-700 text-indigo-600 dark:text-indigo-400 mb-4">
                    <i class="bi bi-geo-alt-fill"></i> Explorar zona
                </div>
                <h1 class="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-slate-900 dark:text-white">
                    Descubre bares y restaurantes
                    <span class="block gradient-text">cerca de tu código postal.</span>
                </h1>
                <p class="mt-3 text-base sm:text-lg text-slate-600 dark:text-slate-300">
                    Selecciona la provincia y el código postal para ver en el mapa los locales de la zona.
                </p>
            </div>

            <form id="zoneForm" class="space-y-6">
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-end">
                    {{-- Provincia --}}
                    <div>
                        <label for="zone_provincia" class="field-label">
                            <i class="bi bi-map"></i>Provincia
                        </label>
                        <select id="zone_provincia" name="zone_provincia" required class="field-input">
                            <option value="">— Seleccionar —</option>
                            @foreach ($provincias as $prov)
                                <option value="{{ $prov }}">{{ $prov }}</option>
                            @endforeach
                        </select>
                    </div>

                    {{-- Código postal --}}
                    <div>
                        <label for="zone_codigo_postal" class="field-label">
                            <i class="bi bi-geo-alt"></i>Código postal
                        </label>
                        <select id="zone_codigo_postal" name="zone_codigo_postal" required class="field-input" disabled>
                            <option value="">— Selecciona una provincia primero —</option>
                        </select>
                    </div>

                    {{-- Botón --}}
                    <div>
                        <button type="submit" class="btn-brand ring-brand w-full inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl text-white font-bold text-base">
                            <i class="bi bi-pin-map-fill text-lg"></i>
                            Ver en el mapa
                        </button>
                    </div>
                </div>
            </form>
        </div>
        {{-- /CARA TRASERA --}}
        @endauth

      </div>
    </div>
    {{-- /HERO FLIP --}}

    {{-- ============================ ESTADO VACÍO ============================ --}}
    <div id="emptyState" class="rounded-2xl border border-dashed border-slate-300 dark:border-slate-700 bg-white/60 dark:bg-slate-900/40 p-16 text-center">
        <div class="w-16 h-16 mx-auto mb-5 rounded-2xl grid place-items-center bg-gradient-to-br from-sky-500/15 to-indigo-500/15 text-indigo-500">
            <i class="bi bi-search text-3xl"></i>
        </div>
        <h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-2">Comienza tu búsqueda</h2>
        <p class="text-slate-600 dark:text-slate-400 max-w-xl mx-auto leading-relaxed">
            Selecciona un tipo de servicio y código postal para encontrar las mejores tarifas disponibles en tu zona.
        </p>
    </div>

    {{-- ============================ RESULTADOS ============================ --}}
    <div id="resultsSection" class="hidden">
        <div class="sticky top-20 z-20 -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8 py-3 mb-4 nav-glass border-b border-slate-200 dark:border-slate-800">
            <div class="max-w-7xl mx-auto flex justify-between items-center flex-wrap gap-3">
                <div class="flex items-center gap-2">
                    <i class="bi bi-lightning-charge-fill text-amber-500 text-xl"></i>
                    <span id="resultsCount" class="text-sm font-bold text-slate-700 dark:text-slate-200">Cargando resultados...</span>
                </div>
                @auth
                    <div class="flex items-center gap-2">
                        <button type="button" class="zone-shortcut-btn" onclick="setMode('zone')">
                            <i class="bi bi-compass"></i>
                            Explorar zona
                        </button>
                        <button id="saveComparisonStickyBtn" type="button" onclick="saveCurrentComparison()" class="hidden inline-flex items-center gap-2 px-4 py-2 rounded-xl border border-indigo-500 text-indigo-600 dark:text-indigo-300 bg-white dark:bg-slate-900 font-bold text-sm hover:bg-indigo-50 dark:hover:bg-slate-800 transition disabled:opacity-50 disabled:cursor-not-allowed">
                            <i class="bi bi-bookmark-fill"></i>
                            <span>Guardar seleccionada</span>
                        </button>
                    </div>
                @endauth
            </div>
        </div>

        <div id="resultsGrid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {{-- Cards generated by JS --}}
        </div>
    </div>

    @auth
    {{-- ============================ MAPA DE ZONA ============================ --}}
    <div id="mapSection" class="hidden">
        <div class="flex items-center justify-between flex-wrap gap-3 mb-4">
            <div class="flex items-center gap-2">
                <i class="bi bi-pin-map-fill text-rose-500 text-xl"></i>
                <span id="mapTitle" class="text-sm font-bold text-slate-700 dark:text-slate-200">Bares y restaurantes en la zona</span>
            </div>
            <a id="mapOpenLink" href="#" target="_blank" rel="noopener" class="hidden inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-bold text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition">
                <i class="bi bi-box-arrow-up-right"></i>Abrir en OpenStreetMap
            </a>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div id="mapFrameWrap" class="map-frame-wrap lg:col-span-2">
                <div id="leafletMap"></div>
            </div>

            <div class="places-list-wrap">
                <div class="places-list-header">
                    <span><i class="bi bi-list-ul me-2"></i><span id="placesCount">Locales</span></span>
                    <div class="flex items-center gap-1">
                        <button type="button" class="place-filter active" data-filter="all">Todo</button>
                        <button type="button" class="place-filter" data-filter="bar">Bares</button>
                        <button type="button" class="place-filter" data-filter="restaurant">Restaur.</button>
                    </div>
                </div>
                <div id="placesList" class="places-list">
                    <div class="places-list-empty">Selecciona una zona para ver locales.</div>
                </div>
            </div>
        </div>
    </div>

    {{-- ============================ ESTADO VACÍO MAPA ============================ --}}
    <div id="mapEmptyState" class="hidden rounded-2xl border border-dashed border-slate-300 dark:border-slate-700 bg-white/60 dark:bg-slate-900/40 p-16 text-center">
        <div class="w-16 h-16 mx-auto mb-5 rounded-2xl grid place-items-center bg-gradient-to-br from-rose-500/15 to-amber-500/15 text-rose-500">
            <i class="bi bi-geo-alt-fill text-3xl"></i>
        </div>
        <h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-2">Explora una zona</h2>
        <p class="text-slate-600 dark:text-slate-400 max-w-xl mx-auto leading-relaxed">
            Selecciona una provincia y un código postal para ver en el mapa los bares y restaurantes disponibles.
        </p>
    </div>
    @endauth

    {{-- ============================ MODAL COMPARATIVA ============================ --}}
    @auth
        <div id="comparisonModal" class="hidden fixed inset-0 bg-slate-900/70 backdrop-blur-md flex items-center justify-center z-50 p-4">
            <div class="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl max-w-2xl w-full max-h-[85vh] overflow-y-auto border border-slate-200 dark:border-slate-700 animate-slideInScale">
                <div class="sticky top-0 p-5 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center">
                    <h3 class="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        <i class="bi bi-bar-chart-fill text-indigo-500"></i>Detalles de comparativa
                    </h3>
                    <button onclick="closeModal()" class="text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 text-2xl leading-none">
                        <i class="bi bi-x-lg"></i>
                    </button>
                </div>
                <div id="modalContent" class="p-6 space-y-4">
                    {{-- AJAX content --}}
                </div>
                <div class="p-5 border-t border-slate-200 dark:border-slate-700 flex gap-3">
                    <button onclick="exportPdf()" class="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold transition">
                        <i class="bi bi-file-earmark-pdf"></i>Descargar PDF
                    </button>
                    <button onclick="closeModal()" class="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-900 dark:text-white font-bold transition">
                        Cerrar
                    </button>
                </div>
            </div>
        </div>
    @endauth
</div>

@endsection

@section('scripts')
<script>
// Mapa provincia => [codigos postales] (inyectado desde el controlador)
const cpsPorProvincia = @json($cpsPorProvincia);

// Inicializar Tom Select sobre el select de CP (vacío inicialmente)
const cpSelect = new TomSelect('#codigo_postal', {
    create: false,
    placeholder: 'Selecciona una provincia primero',
    searchField: ['text', 'value'],
    maxOptions: 500,
});
cpSelect.disable();

// Cuando cambia la provincia, repoblar opciones de CP
const provinciaSelect = document.getElementById('provincia');
provinciaSelect.addEventListener('change', function () {
    const prov = this.value;
    cpSelect.clear();
    cpSelect.clearOptions();

    if (!prov || !cpsPorProvincia[prov]) {
        cpSelect.disable();
        cpSelect.settings.placeholder = 'Selecciona una provincia primero';
        cpSelect.inputState();
        return;
    }

    const opts = cpsPorProvincia[prov].map(cp => ({ value: cp, text: cp }));
    cpSelect.addOptions(opts);
    cpSelect.enable();
    cpSelect.settings.placeholder = 'Buscar código postal...';
    cpSelect.inputState();
});

const isAuthenticated = {{ auth()->check() ? 'true' : 'false' }};
const searchUrl = @json(route('search.query'));
const exportPdfUrl = @json(route('export-pdf'));
const comparisonUrlTemplate = @json(url('/comparacion/__ID__'));
let currentComparacionId = null;
let currentTarifaId = null;
let currentComparisonData = null;
let selectedChips = new Set();

function updateSaveButtonState() {
    const saveButton = document.getElementById('saveComparisonStickyBtn');
    if (!saveButton) return;
    const hasComparison = Boolean(currentComparacionId);
    saveButton.classList.toggle('hidden', !hasComparison);
    saveButton.disabled = !hasComparison;
}

const providerColors = {
    'Endesa': 'endesa',
    'Iberdrola': 'iberdrola',
    'EDF': 'edf',
    'Naturgy': 'naturgy',
    'Telefónica': 'telefonica',
    'Vodafone': 'vodafone',
};

function toggleAdvancedFilters() {
    const filters = document.getElementById('advancedFilters');
    const toggleText = document.getElementById('filterToggleText');
    filters.classList.toggle('hidden');
    toggleText.textContent = filters.classList.contains('hidden')
        ? 'Mostrar filtros avanzados'
        : 'Ocultar filtros avanzados';
}

function toggleChip(button, value) {
    button.classList.toggle('active');
    if (selectedChips.has(value)) {
        selectedChips.delete(value);
    } else {
        selectedChips.add(value);
    }
}

function resetFilters() {
    document.getElementById('min_precio').value = '';
    document.getElementById('max_precio').value = '';
    document.getElementById('buscar_nombre').value = '';
    document.getElementById('ordenar_por').value = 'precio_asc';
    document.querySelectorAll('.chip').forEach(chip => chip.classList.remove('active'));
    selectedChips.clear();
}

const clearFiltersBtn = document.getElementById('clearFiltersBtn');
if (clearFiltersBtn) {
    clearFiltersBtn.addEventListener('click', function(e) {
        e.preventDefault();
        resetFilters();
    });
}

function generateBadge(tarifa, index) {
    if (tarifa.condiciones && tarifa.condiciones.toLowerCase().includes('renovable')) {
        return '<span class="badge-eco"><i class="bi bi-leaf"></i>Eco</span>';
    }
    if (index === 0) {
        return '<span class="badge-bestseller"><i class="bi bi-star-fill"></i>Top precio</span>';
    }
    if (!tarifa.permanencia || tarifa.permanencia === 'Sin permanencia') {
        return '<span class="badge-sin-permanencia"><i class="bi bi-unlock"></i>Sin permanencia</span>';
    }
    return '';
}

function generateBenefits(tarifa) {
    const benefits = [];
    if (tarifa.permanencia) {
        benefits.push(`<div class="benefit-item"><i class="bi bi-calendar-check"></i><span>${tarifa.permanencia}</span></div>`);
    }
    if (tarifa.unidad_precio) {
        const unidadIcon = tarifa.unidad_precio.includes('Mbps') ? 'lightning' :
                          tarifa.unidad_precio.includes('GB') ? 'cloud-download' : 'graph-up';
        benefits.push(`<div class="benefit-item"><i class="bi bi-${unidadIcon}"></i><span>${tarifa.unidad_precio}</span></div>`);
    }
    if (tarifa.condiciones) {
        const isEco = tarifa.condiciones.toLowerCase().includes('renovable');
        const icon = isEco ? 'leaf' : 'info-circle';
        const clase = isEco ? 'eco' : '';
        benefits.push(`<div class="benefit-item ${clase}"><i class="bi bi-${icon}"></i><span class="text-xs">${tarifa.condiciones.substring(0, 40)}...</span></div>`);
    }
    return benefits.slice(0, 3).join('');
}

document.getElementById('searchForm').addEventListener('submit', async (e) => {
    e.preventDefault();

    currentComparacionId = null;
    currentTarifaId = null;
    currentComparisonData = null;
    updateSaveButtonState();

    const tipoServicio = document.getElementById('id_tipo_servicio').value;
    const codigoPostal = document.getElementById('codigo_postal').value;

    if (!tipoServicio || !codigoPostal) {
        alert('Por favor completa los campos requeridos');
        return;
    }

    const emptyState = document.getElementById('emptyState');
    const resultsSection = document.getElementById('resultsSection');
    const resultsGrid = document.getElementById('resultsGrid');

    emptyState.classList.remove('hidden');
    resultsSection.classList.add('hidden');
    emptyState.innerHTML = `
        <div class="text-center py-8">
            <div class="spinner-modern mb-5"></div>
            <p class="text-slate-700 dark:text-slate-200 font-semibold text-lg">Buscando mejores tarifas…</p>
            <p class="text-slate-500 dark:text-slate-400 text-sm mt-1">Esto solo tomará un instante</p>
        </div>
    `;

    try {
        const filters = {
            codigo_postal: codigoPostal,
            id_tipo_servicio: tipoServicio,
        };

        const minPrecio = document.getElementById('min_precio')?.value;
        if (minPrecio) filters.min_precio = minPrecio;

        const maxPrecio = document.getElementById('max_precio')?.value;
        if (maxPrecio) filters.max_precio = maxPrecio;

        const ordenarPor = document.getElementById('ordenar_por')?.value;
        if (ordenarPor) filters.ordenar_por = ordenarPor;

        const buscarNombre = document.getElementById('buscar_nombre')?.value;
        if (buscarNombre) filters.buscar_nombre = buscarNombre;

        if (selectedChips.size > 0) filters.permanencia = Array.from(selectedChips);

        const response = await axios.post(searchUrl, filters);

        const result = response.data?.data || response.data;
        const tarifas = result?.tarifas || [];
        currentComparacionId = result?.comparacion_id || null;
        currentTarifaId = tarifas[0]?.id_tarifa || null;
        currentComparisonData = tarifas[0] || null;
        updateSaveButtonState();

        if (tarifas.length === 0) {
            resultsSection.classList.add('hidden');
            emptyState.classList.remove('hidden');
            emptyState.innerHTML = `
                <div class="text-center py-8">
                    <div class="w-16 h-16 mx-auto mb-5 rounded-2xl grid place-items-center bg-slate-100 dark:bg-slate-800 text-slate-400">
                        <i class="bi bi-inbox text-3xl"></i>
                    </div>
                    <h3 class="text-2xl font-bold text-slate-900 dark:text-white mb-2">Sin tarifas disponibles</h3>
                    <p class="text-slate-600 dark:text-slate-400">No encontramos tarifas para este servicio y código postal. Intenta con otros filtros.</p>
                </div>
            `;
            return;
        }

        emptyState.classList.add('hidden');
        resultsSection.classList.remove('hidden');
        document.getElementById('resultsCount').innerHTML = `
            <i class="bi bi-lightning-charge-fill text-amber-500 me-2"></i>
            ${tarifas.length} tarifa${tarifas.length !== 1 ? 's' : ''} encontrada${tarifas.length !== 1 ? 's' : ''}
        `;

        resultsGrid.innerHTML = tarifas.map((tarifa, idx) => {
            const accentBar = {
                'Endesa': 'from-rose-500 to-red-500',
                'Iberdrola': 'from-emerald-500 to-teal-500',
                'EDF': 'from-orange-500 to-amber-500',
                'Naturgy': 'from-sky-500 to-cyan-500',
                'Telefónica': 'from-indigo-500 to-purple-500',
                'Vodafone': 'from-rose-500 to-pink-500',
            }[tarifa.proveedor?.nombre] || 'from-slate-400 to-slate-500';

            const badge = generateBadge(tarifa, idx);

            return `
                <div class="result-card animate-fadeInUp" style="animation-delay: ${idx * 0.05}s">
                    <div class="h-1.5 w-full bg-gradient-to-r ${accentBar}"></div>
                    <div class="p-5 flex items-center gap-3 border-b border-slate-100 dark:border-slate-800">
                        ${tarifa.proveedor?.logo
                            ? `<img src="${tarifa.proveedor.logo}" alt="${tarifa.proveedor.nombre}" class="w-12 h-12 rounded-lg object-cover flex-shrink-0">`
                            : `<div class="w-12 h-12 rounded-lg bg-gradient-to-br ${accentBar} grid place-items-center text-white font-bold flex-shrink-0">${(tarifa.proveedor?.nombre ?? '?').charAt(0)}</div>`
                        }
                        <div class="flex-grow min-w-0">
                            <div class="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">${tarifa.proveedor?.nombre ?? 'Proveedor'}</div>
                            <div class="text-base font-bold text-slate-900 dark:text-white truncate">${tarifa.nombre_tarifa}</div>
                        </div>
                        ${badge ? `<div>${badge}</div>` : ''}
                    </div>

                    <div class="p-5 bg-gradient-to-br from-sky-50 to-indigo-50 dark:from-sky-950/40 dark:to-indigo-950/40 border-b border-slate-100 dark:border-slate-800">
                        <div class="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">Precio</div>
                        <div class="flex items-baseline gap-1">
                            <span class="text-4xl font-black gradient-text">€${parseFloat(tarifa.precio).toFixed(2)}</span>
                            <span class="text-sm font-semibold text-slate-500 dark:text-slate-400">/${tarifa.unidad_precio || 'mes'}</span>
                        </div>
                    </div>

                    <div class="p-4 flex flex-wrap gap-1 border-b border-slate-100 dark:border-slate-800 min-h-[3rem]">
                        ${generateBenefits(tarifa) || '<span class="text-xs text-slate-400">Sin condiciones extra</span>'}
                    </div>

                    <div class="p-4 flex flex-col gap-2 mt-auto">
                        ${isAuthenticated ? `
                            <button type="button" onclick='viewComparison(${result.comparacion_id}, ${JSON.stringify(tarifa).replace(/'/g, "&#39;")})' class="btn-brand ring-brand w-full inline-flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl text-white font-bold text-sm">
                                <i class="bi bi-eye-fill"></i><span>Ver detalles</span>
                            </button>
                        ` : ''}
                        ${tarifa.url_oferta_externa ? `
                            <a href="${tarifa.url_oferta_externa}" target="_blank" rel="noopener" class="w-full inline-flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-bold text-sm hover:opacity-90 transition">
                                <i class="bi bi-box-arrow-up-right"></i><span>Ver oferta</span>
                            </a>
                        ` : ''}
                    </div>
                </div>
            `;
        }).join('');

    } catch (error) {
        console.error('Error:', error);
        resultsSection.classList.add('hidden');
        emptyState.classList.remove('hidden');
        emptyState.innerHTML = `
            <div class="text-center py-8">
                <div class="w-16 h-16 mx-auto mb-5 rounded-2xl grid place-items-center bg-rose-100 dark:bg-rose-950/40 text-rose-500">
                    <i class="bi bi-exclamation-triangle-fill text-3xl"></i>
                </div>
                <h3 class="text-2xl font-bold text-rose-700 dark:text-rose-300 mb-2">Error en la búsqueda</h3>
                <p class="text-rose-600 dark:text-rose-400">Por favor intenta de nuevo más tarde</p>
            </div>
        `;
    }
});

function closeModal() {
    document.getElementById('comparisonModal').classList.add('hidden');
}

async function viewComparison(comparacionId, tarifaData) {
    if (!isAuthenticated) return;

    try {
        currentComparacionId = comparacionId;
        currentTarifaId = tarifaData.id_tarifa || null;
        currentComparisonData = tarifaData;
        updateSaveButtonState();

        const html = `
            <div class="space-y-4">
                <div class="p-5 rounded-xl bg-gradient-to-br from-sky-50 to-indigo-50 dark:from-sky-950/40 dark:to-indigo-950/40 border border-sky-100 dark:border-sky-900">
                    <div class="flex items-start gap-3 mb-3">
                        ${tarifaData.proveedor?.logo ? `<img src="${tarifaData.proveedor.logo}" alt="" class="w-12 h-12 rounded-lg object-cover">` : ''}
                        <div class="flex-grow">
                            <p class="text-[10px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-300">Proveedor</p>
                            <h3 class="text-xl font-extrabold text-slate-900 dark:text-white">${tarifaData.proveedor?.nombre ?? 'Proveedor'}</h3>
                            <p class="text-sm text-slate-700 dark:text-slate-300">${tarifaData.nombre_tarifa}</p>
                        </div>
                    </div>

                    <div class="border-t border-sky-200 dark:border-sky-800 pt-3 mt-3">
                        <p class="text-[10px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-300 mb-1">Precio mensual</p>
                        <div class="flex items-baseline gap-2">
                            <span class="text-4xl font-black gradient-text">€${parseFloat(tarifaData.precio).toFixed(2)}</span>
                            <span class="text-sm text-slate-700 dark:text-slate-300">/${tarifaData.unidad_precio || 'mes'}</span>
                        </div>
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-3">
                    ${tarifaData.permanencia ? `
                        <div class="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
                            <p class="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1"><i class="bi bi-calendar-check"></i> Permanencia</p>
                            <p class="text-sm font-bold text-slate-900 dark:text-white">${tarifaData.permanencia}</p>
                        </div>
                    ` : ''}
                    ${tarifaData.unidad_precio ? `
                        <div class="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
                            <p class="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1"><i class="bi bi-lightning"></i> Unidad</p>
                            <p class="text-sm font-bold text-slate-900 dark:text-white">${tarifaData.unidad_precio}</p>
                        </div>
                    ` : ''}
                </div>

                ${tarifaData.condiciones ? `
                    <div class="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-100 dark:border-emerald-900">
                        <p class="text-[10px] font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-300 mb-1"><i class="bi bi-check2-circle"></i> Características</p>
                        <p class="text-sm text-emerald-900 dark:text-emerald-100">${tarifaData.condiciones}</p>
                    </div>
                ` : ''}

                ${tarifaData.servicio?.nombre_servicio ? `
                    <div class="p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                        <p class="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1"><i class="bi bi-tag"></i> Tipo de servicio</p>
                        <p class="text-sm font-bold text-slate-900 dark:text-white">${tarifaData.servicio.nombre_servicio}</p>
                    </div>
                ` : ''}
            </div>
        `;

        document.getElementById('modalContent').innerHTML = html;
        document.getElementById('comparisonModal').classList.remove('hidden');
    } catch (error) {
        console.error('Error:', error);
        alert('Error al cargar los detalles');
    }
}

async function saveComparisonFromSearch(comparacionId) {
    if (!isAuthenticated) return;

    const defaultName = currentComparisonData?.nombre_tarifa
        ? `Comparación ${currentComparisonData.nombre_tarifa}`
        : `Comparación ${new Date().toLocaleDateString('es-ES')}`;

    const nombre = prompt('Nombre para guardar la comparación:', defaultName);
    if (nombre === null) return;

    const trimmedName = nombre.trim();
    if (!trimmedName) {
        alert('Debes indicar un nombre válido');
        return;
    }

    try {
        const response = await axios.post(@json(route('comparison.save')), {
            comparacion_id: comparacionId,
            nombre: trimmedName,
        });

        if (response.data?.success) {
            alert('Comparación guardada correctamente');
        } else {
            alert(response.data?.message || 'No se pudo guardar la comparación');
        }
    } catch (error) {
        console.error('Error:', error);
        alert(error.response?.data?.message || 'Error al guardar la comparación');
    }
}

async function saveCurrentComparison() {
    if (!currentComparacionId) {
        alert('Primero selecciona una comparación');
        return;
    }
    await saveComparisonFromSearch(currentComparacionId);
}

async function exportPdf() {
    if (!currentComparacionId) return;

    try {
        const payload = { comparacion_id: currentComparacionId };
        if (currentTarifaId) payload.tarifa_id = currentTarifaId;

        const response = await axios.post(exportPdfUrl, payload, { responseType: 'blob' });

        const url = window.URL.createObjectURL(response.data);
        const a = document.createElement('a');
        a.href = url;
        a.download = `comparativa-${currentComparacionId}.pdf`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
    } catch (error) {
        console.error('Error:', error);
        alert('Error al descargar PDF');
    }
}

// =================================================================
// MODO ZONA: flip de la tarjeta y mapa de bares/restaurantes
// (solo disponible para usuarios autenticados)
// =================================================================
@auth
const heroFlip = document.getElementById('heroFlip');
const tarifaEmptyState = document.getElementById('emptyState');
const tarifaResultsSection = document.getElementById('resultsSection');
const mapSection = document.getElementById('mapSection');
const mapEmptyState = document.getElementById('mapEmptyState');

let tarifaPrevState = { empty: false, results: true };

function setMode(mode) {
    const isZone = mode === 'zone';
    heroFlip.classList.toggle('flipped', isZone);

    document.querySelectorAll('.mode-tab').forEach(tab => {
        const active = tab.dataset.mode === mode;
        tab.classList.toggle('active', active);
        tab.setAttribute('aria-selected', active ? 'true' : 'false');
    });

    if (isZone) {
        tarifaPrevState = {
            empty: tarifaEmptyState.classList.contains('hidden'),
            results: tarifaResultsSection.classList.contains('hidden'),
        };
        tarifaEmptyState.classList.add('hidden');
        tarifaResultsSection.classList.add('hidden');

        const hasMap = leafletMap !== null && placesMarkers.length > 0;
        mapSection.classList.toggle('hidden', !hasMap);
        mapEmptyState.classList.toggle('hidden', hasMap);
        if (hasMap) setTimeout(() => leafletMap.invalidateSize(), 60);
    } else {
        mapSection.classList.add('hidden');
        mapEmptyState.classList.add('hidden');
        tarifaEmptyState.classList.toggle('hidden', tarifaPrevState.empty);
        tarifaResultsSection.classList.toggle('hidden', tarifaPrevState.results);
    }
}

const urlParams = new URLSearchParams(window.location.search);
if (urlParams.get('mode') === 'zone') {
    setMode('zone');
}

// Provincia -> CP en el formulario de zona (reutiliza cpsPorProvincia)
const zoneCpSelect = new TomSelect('#zone_codigo_postal', {
    create: false,
    placeholder: 'Selecciona una provincia primero',
    searchField: ['text', 'value'],
    maxOptions: 500,
});
zoneCpSelect.disable();

document.getElementById('zone_provincia').addEventListener('change', function () {
    const prov = this.value;
    zoneCpSelect.clear();
    zoneCpSelect.clearOptions();

    if (!prov || !cpsPorProvincia[prov]) {
        zoneCpSelect.disable();
        zoneCpSelect.settings.placeholder = 'Selecciona una provincia primero';
        zoneCpSelect.inputState();
        return;
    }

    const opts = cpsPorProvincia[prov].map(cp => ({ value: cp, text: cp }));
    zoneCpSelect.addOptions(opts);
    zoneCpSelect.enable();
    zoneCpSelect.settings.placeholder = 'Buscar código postal...';
    zoneCpSelect.inputState();
});

// Carga diferida de Leaflet (CSS + JS) la primera vez
let leafletReady = null;
function ensureLeaflet() {
    if (leafletReady) return leafletReady;
    leafletReady = new Promise((resolve, reject) => {
        const css = document.createElement('link');
        css.rel = 'stylesheet';
        css.href = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';
        css.integrity = 'sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=';
        css.crossOrigin = '';
        document.head.appendChild(css);

        const script = document.createElement('script');
        script.src = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';
        script.integrity = 'sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=';
        script.crossOrigin = '';
        script.onload = () => resolve(window.L);
        script.onerror = reject;
        document.head.appendChild(script);
    });
    return leafletReady;
}

let leafletMap = null;
let placesMarkers = [];           // [{ id, marker, place }]
let placesData = [];              // raw places del último query
let activePlaceFilter = 'all';

const PLACE_LABELS = {
    bar: 'Bar',
    restaurant: 'Restaurante',
    cafe: 'Cafetería',
    pub: 'Pub',
    fast_food: 'Comida rápida',
};
const PLACE_ICONS = {
    bar: 'bi-cup-straw',
    restaurant: 'bi-egg-fried',
    cafe: 'bi-cup-hot',
    pub: 'bi-cup-fill',
    fast_food: 'bi-bag',
};

async function geocodePostal(cp, provincia) {
    // Intento 1: query libre con CP + provincia + país (la opción más fiable en España)
    const tryQuery = async (q) => {
        const url = `https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(q)}`;
        const res = await fetch(url, { headers: { 'Accept': 'application/json' } });
        if (!res.ok) return null;
        const data = await res.json();
        if (!data.length) return null;
        return { lat: parseFloat(data[0].lat), lon: parseFloat(data[0].lon) };
    };

    let result = await tryQuery(`${cp} ${provincia} España`);
    if (result) return result;

    // Intento 2: query estructurada (sin mezclar con q)
    const structured = `https://nominatim.openstreetmap.org/search?format=json&limit=1&country=es&postalcode=${encodeURIComponent(cp)}`;
    const res = await fetch(structured, { headers: { 'Accept': 'application/json' } });
    if (res.ok) {
        const data = await res.json();
        if (data.length) return { lat: parseFloat(data[0].lat), lon: parseFloat(data[0].lon) };
    }

    // Intento 3: solo provincia
    result = await tryQuery(`${provincia} España`);
    if (result) return result;

    throw new Error('No se pudo localizar el código postal');
}

async function fetchPlaces(cp, lat, lon) {
    // Buscamos locales que estén:
    //  (a) dentro del polígono del CP (boundary=postal_code), o
    //  (b) etiquetados explícitamente con addr:postcode = cp.
    // Overpass deduplica por id, así que la unión es segura.
    const amenityRe = '^(bar|restaurant|cafe|pub|fast_food)$';
    // Limitamos a España: los CPs no son únicos a nivel mundial (p.ej. 18009 existe
    // también en Ucrania), así que sin esto Overpass devuelve fronteras y locales
    // de otros países que comparten el código.
    const query = `
        [out:json][timeout:25];
        area["ISO3166-1"="ES"][admin_level=2]->.es;
        rel(area.es)["boundary"="postal_code"]["postal_code"="${cp}"]->.cp;
        .cp map_to_area->.cpArea;
        (
          node(area.cpArea)["amenity"~"${amenityRe}"];
          way(area.cpArea)["amenity"~"${amenityRe}"];
          node(area.es)["amenity"~"${amenityRe}"]["addr:postcode"="${cp}"](around:6000,${lat},${lon});
          way(area.es)["amenity"~"${amenityRe}"]["addr:postcode"="${cp}"](around:6000,${lat},${lon});
        );
        out center tags;
    `;
    const res = await fetch('https://overpass-api.de/api/interpreter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: 'data=' + encodeURIComponent(query),
    });
    if (!res.ok) throw new Error('Overpass error ' + res.status);
    const json = await res.json();
    return (json.elements || []).map((el, idx) => {
        const lat = el.lat ?? el.center?.lat;
        const lon = el.lon ?? el.center?.lon;
        if (lat == null || lon == null) return null;
        const tags = el.tags || {};
        return {
            id: `${el.type}-${el.id}`,
            lat, lon,
            name: tags.name || 'Sin nombre',
            amenity: tags.amenity,
            address: [tags['addr:street'], tags['addr:housenumber']].filter(Boolean).join(' '),
            cuisine: tags.cuisine,
            phone: tags.phone || tags['contact:phone'],
            website: tags.website || tags['contact:website'],
        };
    }).filter(Boolean);
}

function buildPopupHtml(place) {
    const parts = [`<div style="font-weight:700;font-size:.95rem;margin-bottom:.2rem">${escapeHtml(place.name)}</div>`];
    parts.push(`<div style="font-size:.75rem;color:#64748b;text-transform:capitalize">${PLACE_LABELS[place.amenity] ?? place.amenity}</div>`);
    if (place.address) parts.push(`<div style="font-size:.75rem;margin-top:.35rem"><i class="bi bi-geo-alt"></i> ${escapeHtml(place.address)}</div>`);
    if (place.cuisine) parts.push(`<div style="font-size:.75rem;text-transform:capitalize"><i class="bi bi-tag"></i> ${escapeHtml(place.cuisine.replaceAll(';', ', '))}</div>`);
    if (place.phone) parts.push(`<div style="font-size:.75rem"><i class="bi bi-telephone"></i> ${escapeHtml(place.phone)}</div>`);
    if (place.website) parts.push(`<div style="font-size:.75rem"><a href="${escapeAttr(place.website)}" target="_blank" rel="noopener"><i class="bi bi-box-arrow-up-right"></i> Sitio web</a></div>`);
    return parts.join('');
}

function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
}
function escapeAttr(s) { return escapeHtml(s); }

function renderPlacesList() {
    const list = document.getElementById('placesList');
    const filtered = activePlaceFilter === 'all'
        ? placesData
        : placesData.filter(p => p.amenity === activePlaceFilter);

    document.getElementById('placesCount').textContent =
        filtered.length === 0 ? 'Sin locales' :
        `${filtered.length} local${filtered.length !== 1 ? 'es' : ''}`;

    if (!filtered.length) {
        list.innerHTML = `<div class="places-list-empty">No hay locales que mostrar con este filtro.</div>`;
        return;
    }

    list.innerHTML = filtered.map(p => {
        const type = p.amenity || 'restaurant';
        const icon = PLACE_ICONS[type] || 'bi-shop';
        const label = PLACE_LABELS[type] || type;
        const meta = [p.address, p.cuisine].filter(Boolean).join(' · ');
        return `
            <div class="place-item" data-id="${p.id}">
                <div class="place-icon ${type}"><i class="bi ${icon}"></i></div>
                <div class="place-info">
                    <div class="place-name" title="${escapeAttr(p.name)}">${escapeHtml(p.name)}</div>
                    <div class="place-meta">
                        <span class="place-tag ${type}">${label}</span>
                        ${meta ? escapeHtml(meta) : ''}
                    </div>
                </div>
            </div>
        `;
    }).join('');

    list.querySelectorAll('.place-item').forEach(el => {
        el.addEventListener('click', () => focusPlace(el.dataset.id));
    });
}

function focusPlace(id) {
    const entry = placesMarkers.find(m => m.id === id);
    if (!entry || !leafletMap) return;
    leafletMap.flyTo([entry.place.lat, entry.place.lon], 18, { duration: .8 });
    entry.marker.openPopup();
    setActiveListItem(id);
}

function setActiveListItem(id) {
    document.querySelectorAll('.place-item').forEach(el => {
        el.classList.toggle('active', el.dataset.id === id);
        if (el.dataset.id === id) el.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
    });
}

document.querySelectorAll('.place-filter').forEach(btn => {
    btn.addEventListener('click', () => {
        document.querySelectorAll('.place-filter').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        activePlaceFilter = btn.dataset.filter;
        renderPlacesList();
        // Mostrar/ocultar markers según filtro
        placesMarkers.forEach(({ marker, place }) => {
            const visible = activePlaceFilter === 'all' || place.amenity === activePlaceFilter;
            if (visible) {
                if (!leafletMap.hasLayer(marker)) marker.addTo(leafletMap);
            } else {
                if (leafletMap.hasLayer(marker)) leafletMap.removeLayer(marker);
            }
        });
    });
});

document.getElementById('zoneForm').addEventListener('submit', async function (e) {
    e.preventDefault();
    const provincia = document.getElementById('zone_provincia').value;
    const cp = document.getElementById('zone_codigo_postal').value;

    if (!provincia || !cp) {
        alert('Selecciona una provincia y un código postal');
        return;
    }

    mapEmptyState.classList.add('hidden');
    mapSection.classList.remove('hidden');
    document.getElementById('placesList').innerHTML = `<div class="places-list-loading"><div class="spinner-modern" style="width:32px;height:32px;border-width:3px;margin-bottom:.6rem"></div>Buscando locales…</div>`;
    document.getElementById('placesCount').textContent = 'Cargando…';

    try {
        const L = await ensureLeaflet();

        // Geocode
        const { lat, lon } = await geocodePostal(cp, provincia);

        // Inicializar / mover mapa
        if (!leafletMap) {
            leafletMap = L.map('leafletMap', { zoomControl: true }).setView([lat, lon], 16);
            L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png', {
                attribution: '&copy; OpenStreetMap, &copy; CARTO',
                maxZoom: 19,
            }).addTo(leafletMap);
        } else {
            leafletMap.setView([lat, lon], 16);
        }

        // Limpiar markers anteriores
        placesMarkers.forEach(({ marker }) => leafletMap.removeLayer(marker));
        placesMarkers = [];

        // Fetch lugares (filtrados estrictamente por el CP)
        placesData = await fetchPlaces(cp, lat, lon);
        placesData.sort((a, b) => a.name.localeCompare(b.name, 'es'));

        // Markers
        placesData.forEach(p => {
            const marker = L.marker([p.lat, p.lon])
                .bindPopup(buildPopupHtml(p))
                .on('click', () => setActiveListItem(p.id))
                .addTo(leafletMap);
            placesMarkers.push({ id: p.id, marker, place: p });
        });

        document.getElementById('mapTitle').textContent = `Bares y restaurantes en ${cp} (${provincia})`;
        const openLink = document.getElementById('mapOpenLink');
        openLink.href = `https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=16/${lat}/${lon}`;
        openLink.classList.remove('hidden');

        renderPlacesList();
        // Forzar refresco por si el contenedor estaba oculto
        setTimeout(() => leafletMap.invalidateSize(), 50);

    } catch (err) {
        console.error(err);
        document.getElementById('placesList').innerHTML = `
            <div class="places-list-empty">
                <i class="bi bi-exclamation-triangle text-rose-500"></i><br>
                ${err.message || 'No se pudo cargar la zona. Intenta de nuevo.'}
            </div>`;
        document.getElementById('placesCount').textContent = 'Error';
    }
});
@endauth
</script>
@endsection
