@extends('layouts.app')

@section('title', 'Buscar tarifas · EasyMove')

@section('content')
<style>
    /* ==== Animations ==== */
    @keyframes fadeInUp {
        from { opacity: 0; transform: translateY(16px); }
        to   { opacity: 1; transform: translateY(0); }
    }
    .animate-fadeInUp { animation: fadeInUp .55s ease-out forwards; }

    @keyframes slideInScale {
        from { opacity: 0; transform: scale(.95); }
        to   { opacity: 1; transform: scale(1); }
    }
    .animate-slideInScale { animation: slideInScale .25s ease-out forwards; }

    @keyframes shimmer {
        0% { background-position: -1000px 0; }
        100% { background-position: 1000px 0; }
    }

    /* ==== Search hero ==== */
    .search-hero {
        position: relative;
        overflow: hidden;
        border-radius: 1.5rem;
        border: 1px solid rgb(226 232 240);
        background:
            radial-gradient(1200px 400px at 0% -10%, rgba(14,165,233,.18), transparent 60%),
            radial-gradient(1000px 360px at 100% 0%, rgba(168,85,247,.18), transparent 60%),
            linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);
    }
    html.dark .search-hero {
        border-color: rgb(30 41 59);
        background:
            radial-gradient(1200px 400px at 0% -10%, rgba(14,165,233,.20), transparent 60%),
            radial-gradient(1000px 360px at 100% 0%, rgba(168,85,247,.18), transparent 60%),
            linear-gradient(180deg, #0f172a 0%, #020617 100%);
    }

    /* ==== Inputs ==== */
    .field-input {
        width: 100%;
        padding: .85rem 1rem;
        border-radius: .75rem;
        border: 1px solid rgb(226 232 240);
        background: rgb(255 255 255);
        color: rgb(15 23 42);
        transition: border-color .2s ease, box-shadow .2s ease, background .2s ease;
    }
    .field-input:focus {
        outline: none;
        border-color: rgb(99 102 241);
        box-shadow: 0 0 0 4px rgba(99,102,241,.18);
    }
    html.dark .field-input {
        background: rgb(15 23 42);
        border-color: rgb(51 65 85);
        color: rgb(241 245 249);
    }
    html.dark .field-input:focus {
        border-color: rgb(129 140 248);
        box-shadow: 0 0 0 4px rgba(129,140,248,.22);
    }

    .field-label {
        display: flex; align-items: center; gap: .5rem;
        font-size: .8rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: .05em;
        color: rgb(71 85 105);
        margin-bottom: .5rem;
    }
    html.dark .field-label { color: rgb(148 163 184); }

    /* ==== Chips ==== */
    .chip {
        padding: .55rem 1.1rem;
        border: 1.5px solid rgb(226 232 240);
        border-radius: 9999px;
        background: rgb(255 255 255);
        color: rgb(71 85 105);
        font-weight: 600;
        font-size: .875rem;
        cursor: pointer;
        transition: all .25s ease;
    }
    html.dark .chip { background: rgb(30 41 59); border-color: rgb(51 65 85); color: rgb(203 213 225); }
    .chip:hover {
        border-color: rgb(99 102 241);
        color: rgb(99 102 241);
        transform: translateY(-1px);
    }
    .chip.active {
        background: linear-gradient(135deg, #0ea5e9, #6366f1);
        border-color: transparent;
        color: white;
        box-shadow: 0 6px 18px -4px rgba(99,102,241,.55);
    }

    /* ==== Result cards (generated by JS) ==== */
    .result-card {
        background: white;
        border: 1px solid rgb(226 232 240);
        border-radius: 1rem;
        overflow: hidden;
        transition: transform .3s ease, box-shadow .3s ease, border-color .3s ease;
        display: flex; flex-direction: column;
    }
    html.dark .result-card { background: rgb(15 23 42); border-color: rgb(51 65 85); }
    .result-card:hover {
        transform: translateY(-4px);
        box-shadow: 0 24px 40px -20px rgba(15,23,42,.25);
        border-color: rgba(99,102,241,.5);
    }

    /* ==== Modern spinner ==== */
    .spinner-modern {
        width: 56px; height: 56px;
        border-radius: 50%;
        border: 4px solid rgba(99,102,241,.18);
        border-top-color: rgb(99 102 241);
        animation: spin 1s linear infinite;
        margin: 0 auto;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    /* ==== Tom Select dark-friendly tweaks ==== */
    .ts-control { padding: .85rem 1rem !important; border-radius: .75rem !important; min-height: auto !important; }
    html.dark .ts-control { background: rgb(15 23 42) !important; border-color: rgb(51 65 85) !important; color: rgb(241 245 249) !important; }
    html.dark .ts-dropdown { background: rgb(15 23 42) !important; border-color: rgb(51 65 85) !important; color: rgb(241 245 249) !important; }
    html.dark .ts-dropdown .option { color: rgb(203 213 225) !important; }
    html.dark .ts-dropdown .active { background: rgb(30 41 59) !important; color: white !important; }

    /* ==== Badges in result cards ==== */
    .badge-eco, .badge-bestseller, .badge-sin-permanencia {
        display: inline-flex; align-items: center; gap: .35rem;
        padding: .25rem .65rem;
        border-radius: 9999px;
        font-size: .7rem; font-weight: 700; text-transform: uppercase; letter-spacing: .04em;
    }
    .badge-eco { background: rgba(16,185,129,.12); color: rgb(5 150 105); }
    .badge-bestseller { background: rgba(245,158,11,.14); color: rgb(180 83 9); }
    .badge-sin-permanencia { background: rgba(99,102,241,.14); color: rgb(67 56 202); }

    /* ==== Benefit items ==== */
    .benefit-item {
        display: inline-flex; align-items: center; gap: .35rem;
        padding: .35rem .65rem;
        border-radius: .5rem;
        font-size: .75rem;
        background: rgb(248 250 252);
        color: rgb(71 85 105);
        margin: .15rem;
    }
    html.dark .benefit-item { background: rgb(30 41 59); color: rgb(203 213 225); }
    .benefit-item.eco { background: rgba(16,185,129,.12); color: rgb(5 150 105); }
</style>

<div class="space-y-8">

    {{-- ============================ HERO + FORMULARIO ============================ --}}
    <div class="search-hero p-6 sm:p-10 shadow-sm">
        <div class="mb-8 max-w-3xl">
            <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-white/70 dark:bg-slate-900/70 border border-slate-200 dark:border-slate-700 text-indigo-600 dark:text-indigo-400 mb-4">
                <i class="bi bi-stars"></i> Comparador inteligente
            </div>
            <h1 class="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-slate-900 dark:text-white">
                Encuentra tu tarifa perfecta
                <span class="block gradient-text">en segundos.</span>
            </h1>
            <p class="mt-3 text-base sm:text-lg text-slate-600 dark:text-slate-300">
                Selecciona el tipo de servicio y tu código postal. Nosotros te enseñamos las mejores opciones disponibles.
            </p>
        </div>

        <form id="searchForm" class="space-y-6">
            @csrf
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-end">
                {{-- Tipo de servicio --}}
                <div>
                    <label for="id_tipo_servicio" class="field-label">
                        <i class="bi bi-list-check"></i>Tipo de servicio
                    </label>
                    <select id="id_tipo_servicio" name="id_tipo_servicio" required class="field-input">
                        <option value="">— Seleccionar —</option>
                        @foreach ($tiposServicios as $tipo)
                            <option value="{{ $tipo->id_tipo_servicio }}">{{ $tipo->nombre }}</option>
                        @endforeach
                    </select>
                </div>

                {{-- Código postal --}}
                <div>
                    <label for="codigo_postal" class="field-label">
                        <i class="bi bi-geo-alt"></i>Código postal
                    </label>
                    <select id="codigo_postal" name="codigo_postal" required class="field-input">
                        <option value="">— Seleccionar —</option>
                        @foreach ($codigosPostales as $codigo)
                            <option value="{{ $codigo }}">{{ $codigo }}</option>
                        @endforeach
                    </select>
                </div>

                {{-- Botón --}}
                <div>
                    <button type="submit" class="btn-brand ring-brand w-full inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl text-white font-bold text-base">
                        <i class="bi bi-search text-lg"></i>
                        Buscar tarifas
                    </button>
                </div>
            </div>

            {{-- ============== FILTROS AVANZADOS (auth only) ============== --}}
            @auth
                <button type="button" id="toggleFiltersBtn" onclick="toggleAdvancedFilters()"
                        class="inline-flex items-center gap-2 text-sm font-semibold text-indigo-600 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-300 transition">
                    <i class="bi bi-sliders"></i>
                    <span id="filterToggleText">Mostrar filtros avanzados</span>
                </button>

                <div id="advancedFilters" class="hidden pt-8 border-t border-slate-200 dark:border-slate-700 space-y-6 animate-fadeInUp">
                    <h3 class="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        <i class="bi bi-funnel-fill text-indigo-500"></i>Filtros avanzados
                    </h3>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label class="field-label"><i class="bi bi-currency-euro"></i>Rango de precio (€/mes)</label>
                            <div class="flex items-center gap-3">
                                <input type="number" id="min_precio" name="min_precio" step="0.01" min="0" placeholder="Mín" class="field-input">
                                <span class="text-slate-400 font-bold">—</span>
                                <input type="number" id="max_precio" name="max_precio" step="0.01" min="0" placeholder="Máx" class="field-input">
                            </div>
                        </div>

                        <div>
                            <label for="ordenar_por" class="field-label"><i class="bi bi-sort-down"></i>Ordenar por</label>
                            <select id="ordenar_por" name="ordenar_por" class="field-input">
                                <option value="precio_asc">Precio: menor a mayor</option>
                                <option value="precio_desc">Precio: mayor a menor</option>
                                <option value="reciente">Más reciente</option>
                                <option value="nombre_asc">Alfabético (A-Z)</option>
                            </select>
                        </div>
                    </div>

                    <div>
                        <label class="field-label"><i class="bi bi-calendar-check"></i>Permanencia</label>
                        <div class="flex flex-wrap gap-2">
                            <button type="button" class="chip" onclick="toggleChip(this, 'sin_permanencia')">Sin permanencia</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '1mes')">1 mes</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '3meses')">3 meses</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '6meses')">6 meses</button>
                            <button type="button" class="chip" onclick="toggleChip(this, '12meses')">12 meses</button>
                        </div>
                    </div>

                    <div>
                        <label for="buscar_nombre" class="field-label"><i class="bi bi-search"></i>Buscar por nombre</label>
                        <input type="text" id="buscar_nombre" name="buscar_nombre" placeholder="Ej: Plan Premium, Básico, Eco…" class="field-input">
                    </div>

                    <div class="flex gap-3 pt-4 border-t border-slate-200 dark:border-slate-700">
                        <button type="submit" id="applyFiltersBtn" class="flex-1 inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold transition">
                            <i class="bi bi-check-lg"></i>Aplicar filtros
                        </button>
                        <button type="button" id="clearFiltersBtn" class="flex-1 inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-900 dark:text-white font-bold transition">
                            <i class="bi bi-arrow-counterclockwise"></i>Limpiar
                        </button>
                    </div>
                </div>
            @endauth
        </form>

        {{-- Aviso para invitados --}}
        @guest
            <div class="mt-6 p-4 rounded-xl bg-gradient-to-r from-sky-50 to-indigo-50 dark:from-sky-950/40 dark:to-indigo-950/40 border border-sky-100 dark:border-sky-900">
                <p class="text-sm text-sky-900 dark:text-sky-200 flex items-start gap-3">
                    <i class="bi bi-info-circle text-lg mt-0.5 flex-shrink-0 text-sky-500"></i>
                    <span>
                        <strong>Modo invitado:</strong> solo verás 2 resultados.
                        <a href="{{ route('login') }}" class="underline font-bold hover:text-sky-700 dark:hover:text-sky-300">Inicia sesión</a> para ver todas las opciones y guardar tus comparaciones.
                    </span>
                </p>
            </div>
        @endguest
    </div>

    {{-- ============================ ESTADO VACÍO ============================ --}}
    <div id="emptyState" class="rounded-2xl border border-dashed border-slate-300 dark:border-slate-700 bg-white/60 dark:bg-slate-900/40 p-16 text-center">
        <div class="w-16 h-16 mx-auto mb-5 rounded-2xl grid place-items-center bg-gradient-to-br from-sky-500/15 to-indigo-500/15 text-indigo-500">
            <i class="bi bi-search text-3xl"></i>
        </div>
        <h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-2">Comienza tu búsqueda</h2>
        <p class="text-slate-600 dark:text-slate-400 max-w-xl mx-auto leading-relaxed">
            Selecciona un tipo de servicio y código postal para encontrar las mejores tarifas disponibles en tu zona.
        </p>
    </div>

    {{-- ============================ RESULTADOS ============================ --}}
    <div id="resultsSection" class="hidden">
        <div class="sticky top-20 z-20 -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8 py-3 mb-4 nav-glass border-b border-slate-200 dark:border-slate-800">
            <div class="max-w-7xl mx-auto flex justify-between items-center flex-wrap gap-3">
                <div class="flex items-center gap-2">
                    <i class="bi bi-lightning-charge-fill text-amber-500 text-xl"></i>
                    <span id="resultsCount" class="text-sm font-bold text-slate-700 dark:text-slate-200">Cargando resultados...</span>
                </div>
                @auth
                    <button id="saveComparisonStickyBtn" type="button" onclick="saveCurrentComparison()" class="hidden inline-flex items-center gap-2 px-4 py-2 rounded-xl border border-indigo-500 text-indigo-600 dark:text-indigo-300 bg-white dark:bg-slate-900 font-bold text-sm hover:bg-indigo-50 dark:hover:bg-slate-800 transition disabled:opacity-50 disabled:cursor-not-allowed">
                        <i class="bi bi-bookmark-fill"></i>
                        <span>Guardar seleccionada</span>
                    </button>
                @endauth
            </div>
        </div>

        <div id="resultsGrid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {{-- Cards generated by JS --}}
        </div>
    </div>

    {{-- ============================ MODAL COMPARATIVA ============================ --}}
    @auth
        <div id="comparisonModal" class="hidden fixed inset-0 bg-slate-900/70 backdrop-blur-md flex items-center justify-center z-50 p-4">
            <div class="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl max-w-2xl w-full max-h-[85vh] overflow-y-auto border border-slate-200 dark:border-slate-700 animate-slideInScale">
                <div class="sticky top-0 p-5 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center">
                    <h3 class="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        <i class="bi bi-bar-chart-fill text-indigo-500"></i>Detalles de comparativa
                    </h3>
                    <button onclick="closeModal()" class="text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 text-2xl leading-none">
                        <i class="bi bi-x-lg"></i>
                    </button>
                </div>
                <div id="modalContent" class="p-6 space-y-4">
                    {{-- AJAX content --}}
                </div>
                <div class="p-5 border-t border-slate-200 dark:border-slate-700 flex gap-3">
                    <button onclick="exportPdf()" class="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold transition">
                        <i class="bi bi-file-earmark-pdf"></i>Descargar PDF
                    </button>
                    <button onclick="closeModal()" class="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-900 dark:text-white font-bold transition">
                        Cerrar
                    </button>
                </div>
            </div>
        </div>
    @endauth
</div>

@endsection

@section('scripts')
<script>
// Inicializar Tom Select
new TomSelect('#codigo_postal', {
    create: false,
    placeholder: 'Buscar código postal...',
    searchField: ['text', 'value'],
    maxOptions: 100,
});

const isAuthenticated = {{ auth()->check() ? 'true' : 'false' }};
const searchUrl = @json(route('search.query'));
const exportPdfUrl = @json(route('export-pdf'));
const comparisonUrlTemplate = @json(url('/comparacion/__ID__'));
let currentComparacionId = null;
let currentTarifaId = null;
let currentComparisonData = null;
let selectedChips = new Set();

function updateSaveButtonState() {
    const saveButton = document.getElementById('saveComparisonStickyBtn');
    if (!saveButton) return;
    const hasComparison = Boolean(currentComparacionId);
    saveButton.classList.toggle('hidden', !hasComparison);
    saveButton.disabled = !hasComparison;
}

const providerColors = {
    'Endesa': 'endesa',
    'Iberdrola': 'iberdrola',
    'EDF': 'edf',
    'Naturgy': 'naturgy',
    'Telefónica': 'telefonica',
    'Vodafone': 'vodafone',
};

function toggleAdvancedFilters() {
    const filters = document.getElementById('advancedFilters');
    const toggleText = document.getElementById('filterToggleText');
    filters.classList.toggle('hidden');
    toggleText.textContent = filters.classList.contains('hidden')
        ? 'Mostrar filtros avanzados'
        : 'Ocultar filtros avanzados';
}

function toggleChip(button, value) {
    button.classList.toggle('active');
    if (selectedChips.has(value)) {
        selectedChips.delete(value);
    } else {
        selectedChips.add(value);
    }
}

function resetFilters() {
    document.getElementById('min_precio').value = '';
    document.getElementById('max_precio').value = '';
    document.getElementById('buscar_nombre').value = '';
    document.getElementById('ordenar_por').value = 'precio_asc';
    document.querySelectorAll('.chip').forEach(chip => chip.classList.remove('active'));
    selectedChips.clear();
}

const clearFiltersBtn = document.getElementById('clearFiltersBtn');
if (clearFiltersBtn) {
    clearFiltersBtn.addEventListener('click', function(e) {
        e.preventDefault();
        resetFilters();
    });
}

function generateBadge(tarifa, index) {
    if (tarifa.condiciones && tarifa.condiciones.toLowerCase().includes('renovable')) {
        return '<span class="badge-eco"><i class="bi bi-leaf"></i>Eco</span>';
    }
    if (index === 0) {
        return '<span class="badge-bestseller"><i class="bi bi-star-fill"></i>Top precio</span>';
    }
    if (!tarifa.permanencia || tarifa.permanencia === 'Sin permanencia') {
        return '<span class="badge-sin-permanencia"><i class="bi bi-unlock"></i>Sin permanencia</span>';
    }
    return '';
}

function generateBenefits(tarifa) {
    const benefits = [];
    if (tarifa.permanencia) {
        benefits.push(`<div class="benefit-item"><i class="bi bi-calendar-check"></i><span>${tarifa.permanencia}</span></div>`);
    }
    if (tarifa.unidad_precio) {
        const unidadIcon = tarifa.unidad_precio.includes('Mbps') ? 'lightning' :
                          tarifa.unidad_precio.includes('GB') ? 'cloud-download' : 'graph-up';
        benefits.push(`<div class="benefit-item"><i class="bi bi-${unidadIcon}"></i><span>${tarifa.unidad_precio}</span></div>`);
    }
    if (tarifa.condiciones) {
        const isEco = tarifa.condiciones.toLowerCase().includes('renovable');
        const icon = isEco ? 'leaf' : 'info-circle';
        const clase = isEco ? 'eco' : '';
        benefits.push(`<div class="benefit-item ${clase}"><i class="bi bi-${icon}"></i><span class="text-xs">${tarifa.condiciones.substring(0, 40)}...</span></div>`);
    }
    return benefits.slice(0, 3).join('');
}

document.getElementById('searchForm').addEventListener('submit', async (e) => {
    e.preventDefault();

    currentComparacionId = null;
    currentTarifaId = null;
    currentComparisonData = null;
    updateSaveButtonState();

    const tipoServicio = document.getElementById('id_tipo_servicio').value;
    const codigoPostal = document.getElementById('codigo_postal').value;

    if (!tipoServicio || !codigoPostal) {
        alert('Por favor completa los campos requeridos');
        return;
    }

    const emptyState = document.getElementById('emptyState');
    const resultsSection = document.getElementById('resultsSection');
    const resultsGrid = document.getElementById('resultsGrid');

    emptyState.classList.remove('hidden');
    resultsSection.classList.add('hidden');
    emptyState.innerHTML = `
        <div class="text-center py-8">
            <div class="spinner-modern mb-5"></div>
            <p class="text-slate-700 dark:text-slate-200 font-semibold text-lg">Buscando mejores tarifas…</p>
            <p class="text-slate-500 dark:text-slate-400 text-sm mt-1">Esto solo tomará un instante</p>
        </div>
    `;

    try {
        const filters = {
            codigo_postal: codigoPostal,
            id_tipo_servicio: tipoServicio,
        };

        const minPrecio = document.getElementById('min_precio')?.value;
        if (minPrecio) filters.min_precio = minPrecio;

        const maxPrecio = document.getElementById('max_precio')?.value;
        if (maxPrecio) filters.max_precio = maxPrecio;

        const ordenarPor = document.getElementById('ordenar_por')?.value;
        if (ordenarPor) filters.ordenar_por = ordenarPor;

        const buscarNombre = document.getElementById('buscar_nombre')?.value;
        if (buscarNombre) filters.buscar_nombre = buscarNombre;

        if (selectedChips.size > 0) filters.permanencia = Array.from(selectedChips);

        const response = await axios.post(searchUrl, filters);

        const result = response.data?.data || response.data;
        const tarifas = result?.tarifas || [];
        currentComparacionId = result?.comparacion_id || null;
        currentTarifaId = tarifas[0]?.id_tarifa || null;
        currentComparisonData = tarifas[0] || null;
        updateSaveButtonState();

        if (tarifas.length === 0) {
            resultsSection.classList.add('hidden');
            emptyState.classList.remove('hidden');
            emptyState.innerHTML = `
                <div class="text-center py-8">
                    <div class="w-16 h-16 mx-auto mb-5 rounded-2xl grid place-items-center bg-slate-100 dark:bg-slate-800 text-slate-400">
                        <i class="bi bi-inbox text-3xl"></i>
                    </div>
                    <h3 class="text-2xl font-bold text-slate-900 dark:text-white mb-2">Sin tarifas disponibles</h3>
                    <p class="text-slate-600 dark:text-slate-400">No encontramos tarifas para este servicio y código postal. Intenta con otros filtros.</p>
                </div>
            `;
            return;
        }

        emptyState.classList.add('hidden');
        resultsSection.classList.remove('hidden');
        document.getElementById('resultsCount').innerHTML = `
            <i class="bi bi-lightning-charge-fill text-amber-500 me-2"></i>
            ${tarifas.length} tarifa${tarifas.length !== 1 ? 's' : ''} encontrada${tarifas.length !== 1 ? 's' : ''}
        `;

        resultsGrid.innerHTML = tarifas.map((tarifa, idx) => {
            const accentBar = {
                'Endesa': 'from-rose-500 to-red-500',
                'Iberdrola': 'from-emerald-500 to-teal-500',
                'EDF': 'from-orange-500 to-amber-500',
                'Naturgy': 'from-sky-500 to-cyan-500',
                'Telefónica': 'from-indigo-500 to-purple-500',
                'Vodafone': 'from-rose-500 to-pink-500',
            }[tarifa.proveedor?.nombre] || 'from-slate-400 to-slate-500';

            const badge = generateBadge(tarifa, idx);

            return `
                <div class="result-card animate-fadeInUp" style="animation-delay: ${idx * 0.05}s">
                    <div class="h-1.5 w-full bg-gradient-to-r ${accentBar}"></div>
                    <div class="p-5 flex items-center gap-3 border-b border-slate-100 dark:border-slate-800">
                        ${tarifa.proveedor?.logo
                            ? `<img src="${tarifa.proveedor.logo}" alt="${tarifa.proveedor.nombre}" class="w-12 h-12 rounded-lg object-cover flex-shrink-0">`
                            : `<div class="w-12 h-12 rounded-lg bg-gradient-to-br ${accentBar} grid place-items-center text-white font-bold flex-shrink-0">${(tarifa.proveedor?.nombre ?? '?').charAt(0)}</div>`
                        }
                        <div class="flex-grow min-w-0">
                            <div class="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">${tarifa.proveedor?.nombre ?? 'Proveedor'}</div>
                            <div class="text-base font-bold text-slate-900 dark:text-white truncate">${tarifa.nombre_tarifa}</div>
                        </div>
                        ${badge ? `<div>${badge}</div>` : ''}
                    </div>

                    <div class="p-5 bg-gradient-to-br from-sky-50 to-indigo-50 dark:from-sky-950/40 dark:to-indigo-950/40 border-b border-slate-100 dark:border-slate-800">
                        <div class="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">Precio</div>
                        <div class="flex items-baseline gap-1">
                            <span class="text-4xl font-black gradient-text">€${parseFloat(tarifa.precio).toFixed(2)}</span>
                            <span class="text-sm font-semibold text-slate-500 dark:text-slate-400">/${tarifa.unidad_precio || 'mes'}</span>
                        </div>
                    </div>

                    <div class="p-4 flex flex-wrap gap-1 border-b border-slate-100 dark:border-slate-800 min-h-[3rem]">
                        ${generateBenefits(tarifa) || '<span class="text-xs text-slate-400">Sin condiciones extra</span>'}
                    </div>

                    <div class="p-4 flex flex-col gap-2 mt-auto">
                        ${isAuthenticated ? `
                            <button type="button" onclick='viewComparison(${result.comparacion_id}, ${JSON.stringify(tarifa).replace(/'/g, "&#39;")})' class="btn-brand ring-brand w-full inline-flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl text-white font-bold text-sm">
                                <i class="bi bi-eye-fill"></i><span>Ver detalles</span>
                            </button>
                        ` : ''}
                        ${tarifa.url_oferta_externa ? `
                            <a href="${tarifa.url_oferta_externa}" target="_blank" rel="noopener" class="w-full inline-flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-bold text-sm hover:opacity-90 transition">
                                <i class="bi bi-box-arrow-up-right"></i><span>Ver oferta</span>
                            </a>
                        ` : ''}
                    </div>
                </div>
            `;
        }).join('');

    } catch (error) {
        console.error('Error:', error);
        resultsSection.classList.add('hidden');
        emptyState.classList.remove('hidden');
        emptyState.innerHTML = `
            <div class="text-center py-8">
                <div class="w-16 h-16 mx-auto mb-5 rounded-2xl grid place-items-center bg-rose-100 dark:bg-rose-950/40 text-rose-500">
                    <i class="bi bi-exclamation-triangle-fill text-3xl"></i>
                </div>
                <h3 class="text-2xl font-bold text-rose-700 dark:text-rose-300 mb-2">Error en la búsqueda</h3>
                <p class="text-rose-600 dark:text-rose-400">Por favor intenta de nuevo más tarde</p>
            </div>
        `;
    }
});

function closeModal() {
    document.getElementById('comparisonModal').classList.add('hidden');
}

async function viewComparison(comparacionId, tarifaData) {
    if (!isAuthenticated) return;

    try {
        currentComparacionId = comparacionId;
        currentTarifaId = tarifaData.id_tarifa || null;
        currentComparisonData = tarifaData;
        updateSaveButtonState();

        const html = `
            <div class="space-y-4">
                <div class="p-5 rounded-xl bg-gradient-to-br from-sky-50 to-indigo-50 dark:from-sky-950/40 dark:to-indigo-950/40 border border-sky-100 dark:border-sky-900">
                    <div class="flex items-start gap-3 mb-3">
                        ${tarifaData.proveedor?.logo ? `<img src="${tarifaData.proveedor.logo}" alt="" class="w-12 h-12 rounded-lg object-cover">` : ''}
                        <div class="flex-grow">
                            <p class="text-[10px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-300">Proveedor</p>
                            <h3 class="text-xl font-extrabold text-slate-900 dark:text-white">${tarifaData.proveedor?.nombre ?? 'Proveedor'}</h3>
                            <p class="text-sm text-slate-700 dark:text-slate-300">${tarifaData.nombre_tarifa}</p>
                        </div>
                    </div>

                    <div class="border-t border-sky-200 dark:border-sky-800 pt-3 mt-3">
                        <p class="text-[10px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-300 mb-1">Precio mensual</p>
                        <div class="flex items-baseline gap-2">
                            <span class="text-4xl font-black gradient-text">€${parseFloat(tarifaData.precio).toFixed(2)}</span>
                            <span class="text-sm text-slate-700 dark:text-slate-300">/${tarifaData.unidad_precio || 'mes'}</span>
                        </div>
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-3">
                    ${tarifaData.permanencia ? `
                        <div class="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
                            <p class="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1"><i class="bi bi-calendar-check"></i> Permanencia</p>
                            <p class="text-sm font-bold text-slate-900 dark:text-white">${tarifaData.permanencia}</p>
                        </div>
                    ` : ''}
                    ${tarifaData.unidad_precio ? `
                        <div class="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
                            <p class="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1"><i class="bi bi-lightning"></i> Unidad</p>
                            <p class="text-sm font-bold text-slate-900 dark:text-white">${tarifaData.unidad_precio}</p>
                        </div>
                    ` : ''}
                </div>

                ${tarifaData.condiciones ? `
                    <div class="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-100 dark:border-emerald-900">
                        <p class="text-[10px] font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-300 mb-1"><i class="bi bi-check2-circle"></i> Características</p>
                        <p class="text-sm text-emerald-900 dark:text-emerald-100">${tarifaData.condiciones}</p>
                    </div>
                ` : ''}

                ${tarifaData.servicio?.nombre_servicio ? `
                    <div class="p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                        <p class="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1"><i class="bi bi-tag"></i> Tipo de servicio</p>
                        <p class="text-sm font-bold text-slate-900 dark:text-white">${tarifaData.servicio.nombre_servicio}</p>
                    </div>
                ` : ''}
            </div>
        `;

        document.getElementById('modalContent').innerHTML = html;
        document.getElementById('comparisonModal').classList.remove('hidden');
    } catch (error) {
        console.error('Error:', error);
        alert('Error al cargar los detalles');
    }
}

async function saveComparisonFromSearch(comparacionId) {
    if (!isAuthenticated) return;

    const defaultName = currentComparisonData?.nombre_tarifa
        ? `Comparación ${currentComparisonData.nombre_tarifa}`
        : `Comparación ${new Date().toLocaleDateString('es-ES')}`;

    const nombre = prompt('Nombre para guardar la comparación:', defaultName);
    if (nombre === null) return;

    const trimmedName = nombre.trim();
    if (!trimmedName) {
        alert('Debes indicar un nombre válido');
        return;
    }

    try {
        const response = await axios.post(@json(route('comparison.save')), {
            comparacion_id: comparacionId,
            nombre: trimmedName,
        });

        if (response.data?.success) {
            alert('Comparación guardada correctamente');
        } else {
            alert(response.data?.message || 'No se pudo guardar la comparación');
        }
    } catch (error) {
        console.error('Error:', error);
        alert(error.response?.data?.message || 'Error al guardar la comparación');
    }
}

async function saveCurrentComparison() {
    if (!currentComparacionId) {
        alert('Primero selecciona una comparación');
        return;
    }
    await saveComparisonFromSearch(currentComparacionId);
}

async function exportPdf() {
    if (!currentComparacionId) return;

    try {
        const payload = { comparacion_id: currentComparacionId };
        if (currentTarifaId) payload.tarifa_id = currentTarifaId;

        const response = await axios.post(exportPdfUrl, payload, { responseType: 'blob' });

        const url = window.URL.createObjectURL(response.data);
        const a = document.createElement('a');
        a.href = url;
        a.download = `comparativa-${currentComparacionId}.pdf`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
    } catch (error) {
        console.error('Error:', error);
        alert('Error al descargar PDF');
    }
}
</script>
@endsection
